version: "3.9"

services:
    server:
        image: fcchang/node-a3
        ports:
            - "8080:8080"
    db:
        image: 'postgres'
        ports:
            - 1234:5432
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'root'
      